# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab9a09e19d907158a6712828e6b0dd4060a1163b740a73b7281d2a023a11ceb0f37c5b14d2045317e263227a894409346736672d437373878f6c8111946f8b10

test:
  secret_key_base: 77db2d279516cb15d6e328cc3d001c567e761f0f5783ea00b2bb5404b640ab7517f2befbc55ec903ceef7b51d96cb95eb38a3beb102a0eb9267c24a6b7bee1ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
